### ISSUE TITLE
Drop minimum Python version to 3.8

### ISSUE THREAD

**Issue by ezwelty** [ezwelty/tablecloth#2]
The package is marked as requiring Python 3.9+, but this is only due to development dependencies. The package runs in 3.8, and making it available for this version would require separating test dependencies from other dev dependencies in `pyproject.toml`, then adjusting the `tests.yaml` GitHub Action workflow.

**Comment by issamansur** [comment]
can I assign this?

**Comment by ezwelty** [comment]
@issamansur certainly!
